---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-demo
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/ashwinidas/podinfo
